### ISSUE TITLE
Bisa di jelaskan kenapa ini di hapus?

### ISSUE THREAD

**Issue by riobahtiar** [Rachmat04/Surel-permintaan-Wikimedia-Indonesia#2]
<img width="1213" alt="screen shot 2018-04-04 at 3 36 54 am" src="https://user-images.githubusercontent.com/2656058/38274605-7a6f8916-37b9-11e8-9739-fc568b127375.png">

Hai Mas @Rachmat04 . Saya salah satu staff di Pesantren Zainul Hasan. dimana halaman wikipedia itu telah dihapus dengan anda. yang menurut saya alasan penghapusannya tidak rasional. Jikapun ada yang salah dalam pages nya bisa dikasih warning untuk diperbaiki. Dalam hal ini saya minta penjelasan lengkapnya. Mohon maaf jika melalui media ini.

Rio Bahtiar

**Comment by Rachmat04** [comment]
_Tidak berhubungan dengan masalah di aplikasi._
